[project]
name = "build-a-llm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.0",
    "numpy>=2.2.3",
    "tiktoken>=0.8.0",
    "torch>=2.6.0",
]
